testSpam : /home/pi/Git/RF24/bcm2835.o /home/pi/Git/RF24/spi.o /home/pi/Git/RF24/RF24.o TestRecieve.C
	g++ -o testRecieve /home/pi/Git/RF24/bcm2835.o /home/pi/Git/RF24/spi.o /home/pi/Git/RF24/RF24.o TestRecieve.C

