bitErrorRateReceive : /home/pi/Git/RF24/bcm2835.o /home/pi/Git/RF24/spi.o /home/pi/Git/RF24/RF24.o BitErrorRateReceive.C
	g++ -o bitErrorRateReceive /home/pi/Git/RF24/bcm2835.o /home/pi/Git/RF24/spi.o /home/pi/Git/RF24/RF24.o BitErrorRateReceive.C

